import React from 'react';
import { FileData } from '../types';
import { FileCheck, Download, Copy, Check } from 'lucide-react';

interface SummaryResultProps {
  summary: string;
  fileData: FileData | null;
  onReset: () => void;
}

const SummaryResult: React.FC<SummaryResultProps> = ({ summary, fileData, onReset }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([summary], {type: 'text/markdown'});
    element.href = URL.createObjectURL(file);
    element.download = `meeting_summary_${new Date().toISOString().slice(0,10)}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (!summary) return null;

  return (
    <div className="w-full max-w-4xl mx-auto mt-8 animate-fade-in-up">
      <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-200">
        
        {/* Header of Result */}
        <div className="bg-gray-50 px-6 py-4 border-b border-gray-200 flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-3">
            <div className="bg-green-100 p-2 rounded-lg">
              <FileCheck className="w-5 h-5 text-green-600" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">Summary Generated</h3>
              {fileData && (
                <p className="text-xs text-gray-500">{fileData.name} • {fileData.type}</p>
              )}
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button 
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied" : "Copy"}
            </button>
            <button 
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <Download className="w-4 h-4" />
              Save MD
            </button>
            <button 
              onClick={onReset}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
            >
              New Summary
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-8 prose prose-blue max-w-none">
          <div className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
            {/* Simple markdown-like rendering simulation by preserving whitespace and minimal styling */}
             {summary.split('\n').map((line, i) => {
                if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold text-gray-900 mt-6 mb-4">{line.replace('# ', '')}</h1>;
                if (line.startsWith('## ')) return <h2 key={i} className="text-xl font-semibold text-gray-800 mt-6 mb-3 border-b pb-2">{line.replace('## ', '')}</h2>;
                if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-semibold text-gray-800 mt-4 mb-2">{line.replace('### ', '')}</h3>;
                if (line.startsWith('- ')) return <li key={i} className="ml-4 list-disc text-gray-700 mb-1">{line.replace('- ', '')}</li>;
                return <p key={i} className="mb-2 text-gray-700">{line}</p>;
             })}
          </div>
        </div>
        
        <div className="bg-gray-50 px-6 py-4 border-t border-gray-200 text-center">
            <p className="text-xs text-gray-400">Generated by Gemini 2.5 Flash • Verify important details from the original recording.</p>
        </div>
      </div>
    </div>
  );
};

export default SummaryResult;
